### ISSUE TITLE
Auto refresh and health check not working  with springboot 2.0.0.M7 and spring-cloud-consul-config 2.0.0.M4

### ISSUE THREAD

**Issue by olehlesiuk** [spring-cloud/spring-cloud-consul#384]
Bug report

**spring-cloud-consul:2.0.0M4 does not work properly after changes in springboot-actuator: 2.0.0M7**

In order to verify that issue is not with my app I generated 2 projects in http://start.spring.io with dependencies: Consul configuration, Consul Discovery, Web

https://github.com/olehlesiuk/demo-spring-boot-1.5.9
@EnableDiscoveryClient
added to generated configuration:
 - @EnableDiscoveryClient
 - config file bootstrap.properties with
spring.application.name=s1pconsuldemo

**health check and auto refresh of configuration is woking properly:**
2018-01-05 10:45:27.150  INFO 77968 --- [pool-1-thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@5ca93be9: startup date [Fri Jan 05 10:45:27 CET 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@6ffa1428
2018-01-05 10:45:27.151  INFO 77968 --- [pool-1-thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6ffa1428: startup date [Fri Jan 05 10:45:26 CET 2018]; root of context hierarchy
2018-01-05 10:45:27.829  INFO 77968 --- [pool-1-thread-1] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [foo]
 

https://github.com/olehlesiuk/demo-springboot-2.0.0.M7
added to generated configuration:
 - @EnableDiscoveryClient
 - config file bootstrap.properties with
spring.application.name=s1pconsuldemo
management.endpoints.web.expose=*

**health check and auto refresh is not working properly. I noticed that in springboot-actuator 2.0.0M7 endpoint was changed to /actuator/health and /actuator/refresh. spring-cloud-consul still has /health**

2018-01-05 10:46:47.787  INFO 78073 --- [           main] o.s.c.c.s.ConsulServiceRegistry          : Registering service with consul: NewService{id='s1pconsuldemo', name='s1pconsuldemo', tags=[], address='192.168.1.119', port=8080, enableTagOverride=null, check=Check{script='null', interval='10s', ttl='null', http='http://192.168.1.119:8080/health', tcp='null', timeout='null', deregisterCriticalServiceAfter='null', tlsSkipVerify=null, status='null'}, checks=null}

**Comment by spencergibb** [comment]
The actuator path has been fixed and is unrelated.

**Comment by olehlesiuk** [comment]
May you  please advise how to properly configure spring cloud consul for this version?

**Comment by szymonzo** [comment]
I have this same issue as well. @spencergibb How we can fix it ?

**Comment by spencergibb** [comment]
Duplicates #345, fixed by 5d7331a648e81ef10e22639ab0099589c4fff893

Trying snapshots should fix the problem.

**Comment by SystemOutPrint** [comment]
snapshots has problem.

`Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.<init>(Lorg/springframework/cloud/client/serviceregistry/ServiceRegistry;Lorg/springframework/cloud/client/serviceregistry/AutoServiceRegistrationProperties;)V
`

**Comment by olehlesiuk** [comment]
adding 'spring.cloud.consul.discovery.health-check-path=/actuator/health' to bootstrap resolve issue with health check, but issue with configuration auto update still exist.

Any idea why auto refresh of configuration from consul stop working in this version?

**Comment by spencergibb** [comment]
@SystemOutPrint you have mismatched versions on your classpath.

@olehlesiuk if you can provide a minimal sample that reproduces the problem, open a new issue.

**Comment by olehlesiuk** [comment]
@spencergibb thank you for advice. Created new issue hope description is good enough:
https://github.com/spring-cloud/spring-cloud-consul/issues/399

**Comment by SystemOutPrint** [comment]
thx
